name: Mark Issue In Progress on Branch Creation

on:
  create:
    branches: [ '**' ]

jobs:
  update-project:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/')
    steps:
      - name: Extract Issue Number from Branch Name
        id: extract
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" =~ ([0-9]+) ]]; then
            echo "issue_number=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "No issue number found"
            exit 1
          fi

      - name: Update Issue Status via GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit "${{ steps.extract.outputs.issue_number }}" \
            --add-project <project_id> \
            --field "Status"="In Progress"
