- name: Update Project Item Status via GitHub CLI
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    ISSUE_NUMBER=${{ steps.extract.outputs.issue_number }}

    # Get the project item ID linked to the issue
    ITEM_ID=$(gh api graphql -f query='
      query ($issueNumber: Int!) {
        repository(owner: "AdrianPeM", name: "forma-frontend") {
          issue(number: $issueNumber) {
            projectItems(first: 10) {
              nodes {
                id
              }
            }
          }
        }
      }
    ' -f issueNumber=$ISSUE_NUMBER --jq '.data.repository.issue.projectItems.nodes[0].id')

    if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" == "null" ]; then
      echo "No project item found for issue #$ISSUE_NUMBER"
      exit 1
    fi

    # Now update the project item status field
    gh project item-edit --id $ITEM_ID \
      --field-id PVTSSF_lAHOA55aJs4A6LFnzgu2GSI \
      --option-id 47fc9ee4
