name: CI - Deployable build

on:
  pull_request:
    branches: [development, main]
    types: [opened, synchronize]

jobs:
  deployment_check:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
            access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build Project
        run: npm run build
